# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev4+g76cbb84.d20230425'
__version_tuple__ = version_tuple = (0, 1, 'dev4', 'g76cbb84.d20230425')
